name: DependencyCheck

run-name: "Periodic check for dependency updates"

on:
  push
  # schedule:
  #   - cron:  '17 4 * * *'

jobs:
  RetrieveTargetsMatrix:
    uses: ./.github/workflows/create-matrix.yml

  CheckForSTReposRelease:
    runs-on: ubuntu-latest
    needs: RetrieveTargetsMatrix
    strategy:
      matrix: ${{ fromJSON(needs.RetrieveTargetsMatrix.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Print Job
        run: echo "Updating ${{ matrix.family }} Family with latest ST tags"
